---
- hosts: 192.168.1.78
  vars:
    git_user_name: "{{ lookup('env', 'GIT_USER_NAME') }}"
    git_user_email: "{{ lookup('env', 'GIT_USER_EMAIL') }}"
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    nfs_server: "{{ lookup('env', 'RPI_NFS_HOMENAS_SERVER') }}"
    nfs_path: "{{ lookup('env', 'RPI_NFS_HOMENAS_PATH') }}"
    mount_point: "{{ lookup('env', 'RPI_MOUNT_POINT') }}"
    nfs_options: "defaults"
    repo_url: "git@github.com:jersme/rpi.git"

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
      become: yes

    - name: Set Git user name
      git_config:
        scope: global
        name: user.name
        value: "{{ git_user_name }}"

    - name: Set Git user email
      git_config:
        scope: global
        name: user.email
        value: "{{ git_user_email }}"

    - name: Generate SSH key
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Add SSH key to GitHub
      uri:
        url: "https://api.github.com/user/keys"
        method: POST
        body_format: json
        headers:
          Authorization: "token {{ github_token }}"
          Content-Type: "application/json"
        body:
          title: "Raspberry Pi SSH Key"
          key: "{{ lookup('file', ansible_env.HOME + '/.ssh/id_rsa.pub') }}"
      delegate_to: localhost

    - name: Create user directories
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - repos
        - tmp
        - envs
        - downloads

    - name: Install NFS client utilities
      apt:
        name: nfs-common
        state: present
      become: yes

    - name: Create the mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'
      become: yes

    - name: Add NFS mount to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ nfs_server }}:{{ nfs_path }} {{ mount_point }} nfs {{ nfs_options }} 0 0"
        state: present
      become: yes

    - name: Mount all filesystems in /etc/fstab
      command: mount -a
      become: yes

    - name: Clone the specified Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ ansible_env.HOME }}/repos/rpi"
        accept_hostkey: yes
